# Generated by Django 5.1.7 on 2025-03-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('transmission', models.CharField(max_length=50)),
                ('mileage', models.IntegerField()),
                ('fuelType', models.CharField(max_length=50)),
                ('tax', models.IntegerField()),
                ('mpg', models.FloatField()),
                ('engineSize', models.FloatField()),
            ],
        ),
    ]
